(* open Gss *)
(* open Gss_stack *)
(* open Domain_types *)

(* let debug_iteration_start stacks_count = *)
(*   Printf.printf "construct_ast: processing %d stacks\n%!" stacks_count *)
(* ;; *)

(* let get_next_actions_for_stack_direction g stack = *)
(*   if stack.direction = Forward *)
(*   then get_next_actions_for_stack (get_forward_parse_table g.parse_tables) stack *)
(*   else get_next_actions_for_stack (get_backward_parse_table g.parse_tables) stack *)
(* ;; *)

(* let filter_stacks_with_actions *)
(*       (stack_action_pairs : (stack * (gss_node * action list) list) list) *)
(*   = *)
(*   stack_action_pairs *)
(*   |> *)
(*   let filter_empty_action_lists = *)
(*     List.filter (fun (node, action_list) -> action_list <> []) *)
(*   in *)
(*   let filter_top_nodes_with_no_actions = List.map filter_empty_action_lists in *)
(*   List.filter (fun (s, top_nodes) -> top_nodes <> []) *)
(* ;; *)

(* let next_action_for_stacks (g : graph) = *)
(*   List.map (fun s -> s, get_next_actions_for_stack_direction g s) g.stacks *)
(* ;; *)

(* let get_all_actions (g : graph) = *)
(*   next_action_for_stacks g |> filter_stacks_with_actions |> List.split *)
(* ;; *)
